### ISSUE TITLE
Chargement Ajax

### ISSUE THREAD

**Issue by qwertygc** [DMeloni/shaarlo#12]
Salut ! Une idée parmi tant d'autres : Une option qui est un peu ce que j'appellerai un mur. En gros, toutes les entrées shaarli, mais à un moment, on charge le reste en Ajax (un défilement infini quoi). Pas pratique par jour, je trouve (enfin si, mais pas dans tout les cas).

**Comment by DMeloni** [comment]
L'option "Activer le scroll infini" permet de contourner les préférences =)
