### ISSUE TITLE
Pas de discussion sur les vidéos ?

### ISSUE THREAD

**Issue by tcitworld** [DMeloni/shaarlo#15]
Actuellement sur Shaarlo : ☉FAUVE ≠ BLIZZARD (VERSION LONGUE) - YouTube partagé à la fois par moi sur tcit's links et aussi par Les liens de Raph. Pourtant, ce n'est pas dans une discussion.
Une idée ?

C'est exactement la même URL pourtant : http://www.youtube.com/watch?v=HMpmedi_pH4#at=101

**Comment by DMeloni** [comment]
C'est chose faite pour le https/http (depuis quelques mois déjà)

**Comment by Draky50110** [comment]
Ho !
Vieille remontée :p 
De toute façon j'utilise la version d'avant "my" moi ;)
