### ISSUE TITLE
Gestions des tags

### ISSUE THREAD

**Issue by Knah-Tsaeb** [DMeloni/shaarlo#34]
Salut,
Shaarli par défaut exporte la liste des tags dans les fluxs. Peut être qu'il serais intéressant de les afficher dans Shaarlo. Je ne sais pas ce qui est le mieux pour les liens sur les tags :
  * renvoyer sur le Shaarli de l'auteur http://example.org/?searchtags=tags
  * renvoyer les posts qui comporte le tag en question dans Shaarlo

A voir.
Bon courage pour la suite et merci pour Shaarlo.

**Comment by DMeloni** [comment]
Fut un temps les tags étaient présents et faisaient une recherche sur shaarlo.
A voir quel choix prendre. 

Le code à faire est pas super intéressant (récupérer tous les tags, les dédoublonner et rajouter les liens avant insertion dans le xsl).

A voir :-)

**Comment by DMeloni** [comment]
(Un peu en retard xd)
