### ISSUE TITLE
Voir la liste des shaarli en public

### ISSUE THREAD

**Issue by tcitworld** [DMeloni/shaarlo#9]
Salut,

Vu que le panneau d'admin est mis en place, pourrait-on avoir une liste publique des shaarlis intégrés ?
Un super truc serait encore un export/import de la liste publique, mais faut pas exagérer non plus.
Si ?

**Comment by DMeloni** [comment]
Oui le mod opml devient obsolète. 
J'avais pas du tout vu passer ce fil l'été dernier (honte à moi...), c'était surement cette faille qu'un mec avait utilisé pour foutre en l'air la page d'admin.
